name: Android WebdriverIO Native Demo App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ios/**'
      - '**.md'
      - '**/ios.yml'
defaults:
  run:
    working-directory: android
jobs:
  ReleaseBuild:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build Android Release
        run: yarn android.release
      - name: Archive Apps
        uses: actions/upload-artifact@v2
        with:
          name: Android WebdriverIO Native Demo App Release
          path: '**/app/build/outputs/apk/release/**/*.apk'
